hydra:
  run:
    dir: ./data/.hydra
  output_subdir: null

seed: 42
n_splits: 4
debug: False
is_eval: True

path:
  features: ./data/feature
  model: ./data/model
  train: ./data/train

features:
  - text_length
  - word_count
  - sentence_count
  - quoted_sentence_count
  - consecutive_dots_count
  - quotes_count
  - word_overlap_count
  - spell_miss_count
  - ngram_co_occurrence_count
  - deberta_text_embeddings
  # - deberta_prompt_embeddings

defaults:
  - _self_
  - model: xgb
