hydra:
  run:
    dir: ./data/.hydra
  output_subdir: null

seed: 42
n_splits: 5
debug: False
is_eval: True

features:
  - text_length
  - word_count
  - sentence_count
  - quoted_sentence_count
  - consecutive_dots_count

defaults:
  - _self_
  - model: xgb
